<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class AuditTrail_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

     // public function get_data($id){
     //      return $this->db->select('*')
     //                  ->from('user_audit_trails')
     //                    ->where(['id'=>$id])
     //                    ->get()
     //                    ->row();
     // }

    public function get_data_audit($id)
    {
        $params = array('id'=>$id);
        $data['audit'] = $this->db->get_where('user_audit_trails',$params)->result();
        $this->load->view('auditTrail/view_data_auditrail', $data);
    }
}

/* End of file School_model.php */
/* Location: ./application/models/School_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-24 16:38:39 */