<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Classroom_model extends CI_Model
{

    public $table = 'classroom';
    public $id = 'class_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('class_id,class_name,class_type,class_status,school_id');
        $this->datatables->from('classroom');

        $this->datatables->add_column('action', 
                anchor(site_url('classroom/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> View', array('class' => 'btn btn-success btn-sm', 'title' => 'view Record')).
                " | "
                .anchor(site_url('classroom/update/$1'),'<i class="mdi mdi-lead-pencil" aria-hidden="true"></i> Update', array('class' => 'btn btn-cyan btn-sm')).
                " | "
                .anchor(site_url('classroom/delete/$1'),'<i class="mdi mdi-delete-forever" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-sm delete-btn')), 'class_id');
        return $this->datatables->generate();

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('class_id', $q);
		$this->db->or_like('class_name', $q);
		$this->db->or_like('class_type', $q);
		$this->db->or_like('class_status', $q);
		$this->db->or_like('school_id', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('class_id', $q);
		$this->db->or_like('class_name', $q);
		$this->db->or_like('class_type', $q);
		$this->db->or_like('class_status', $q);
		$this->db->or_like('school_id', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Classroom_model.php */
/* Location: ./application/models/Classroom_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-31 07:52:34 */