<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dynamic_country_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    function fetch_country()
     {
          // $this->db->order_by("name", "ASC");
     	  $id = "132"; // set to malaysia
     	  $this->db->where('id', $id);
          $query = $this->db->get("master_country");
          return $query->result();
     }

     function fetch_state($id)
     {
          $this->db->where('country_id', $id);
          $this->db->order_by('name', 'ASC');
          $query = $this->db->get('master_state');
          $output = '<option value="">- Pilih Negeri -</option>';
          foreach($query->result() as $row)
          {
           $output .= '<option value="'.$row->id.'">'.$row->name.'</option>';
          }
          return $output;
     }

     function fetch_city($id)
     {
          $this->db->where('state_id', $id);
          $this->db->order_by('name', 'ASC');
          $query = $this->db->get('master_city');
          $output = '<option value="">- Pilih Bandar -</option>';
          foreach($query->result() as $row)
          {
           $output .= '<option value="'.$row->id.'">'.$row->name.'</option>';
          }
          return $output;
     }

}

/* End of file School_model.php */
/* Location: ./application/models/School_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-24 16:38:39 */