<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class School_model extends CI_Model
{

    public $table = 'school';
    public $id = 'school_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('school_id,school_name,school_address,school_postal_code,school_city_id,school_state_id,school_country_id,school_type,school_level,create_at,update_at');
        $this->datatables->from('school');

        $this->datatables->add_column('action', 
                anchor(site_url('school/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> View', array('class' => 'btn btn-success btn-sm', 'title' => 'view Record')).
                " | "
                .anchor(site_url('school/update/$1'),'<i class="mdi mdi-lead-pencil" aria-hidden="true"></i> Update', array('class' => 'btn btn-cyan btn-sm')).
                " | "
                .anchor(site_url('school/delete/$1'),'<i class="mdi mdi-delete-forever" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-sm delete-btn')), 'school_id');
        return $this->datatables->generate();

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('school_id', $q);
		$this->db->or_like('school_name', $q);
		$this->db->or_like('school_address', $q);
		$this->db->or_like('school_postal_code', $q);
		$this->db->or_like('school_city_id', $q);
		$this->db->or_like('school_state_id', $q);
		$this->db->or_like('school_country_id', $q);
		$this->db->or_like('school_type', $q);
		$this->db->or_like('school_level', $q);
		$this->db->or_like('create_at', $q);
		$this->db->or_like('update_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('school_id', $q);
		$this->db->or_like('school_name', $q);
		$this->db->or_like('school_address', $q);
		$this->db->or_like('school_postal_code', $q);
		$this->db->or_like('school_city_id', $q);
		$this->db->or_like('school_state_id', $q);
		$this->db->or_like('school_country_id', $q);
		$this->db->or_like('school_type', $q);
		$this->db->or_like('school_level', $q);
		$this->db->or_like('create_at', $q);
		$this->db->or_like('update_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file School_model.php */
/* Location: ./application/models/School_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-07 16:46:59 */