<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Teacher_model extends CI_Model
{

    public $table = 'teacher';
    public $id = 'tch_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('tch_id,tch_staff_no,tch_fullname,tch_nric_no,tch_contact_no,tch_gender,tch_phone_no,tch_email,tch_race,tch_religion,tch_address,tch_postal_code,tch_city_id,tch_state_id,tch_country_id,school_id,create_at,update_at');
        $this->datatables->from('teacher');

        $this->datatables->add_column('action', 
                anchor(site_url('teacher/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> View', array('class' => 'btn btn-success btn-sm', 'title' => 'view Record')).
                " | "
                .anchor(site_url('teacher/update/$1'),'<i class="mdi mdi-lead-pencil" aria-hidden="true"></i> Update', array('class' => 'btn btn-cyan btn-sm')).
                " | "
                .anchor(site_url('teacher/delete/$1'),'<i class="mdi mdi-delete-forever" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-sm delete-btn')), 'tch_id');
        return $this->datatables->generate();

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('tch_id', $q);
		$this->db->or_like('tch_staff_no', $q);
		$this->db->or_like('tch_fullname', $q);
		$this->db->or_like('tch_nric_no', $q);
		$this->db->or_like('tch_contact_no', $q);
		$this->db->or_like('tch_gender', $q);
		$this->db->or_like('tch_phone_no', $q);
		$this->db->or_like('tch_email', $q);
		$this->db->or_like('tch_race', $q);
		$this->db->or_like('tch_religion', $q);
		$this->db->or_like('tch_address', $q);
		$this->db->or_like('tch_postal_code', $q);
		$this->db->or_like('tch_city_id', $q);
		$this->db->or_like('tch_state_id', $q);
		$this->db->or_like('tch_country_id', $q);
		$this->db->or_like('school_id', $q);
		$this->db->or_like('create_at', $q);
		$this->db->or_like('update_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tch_id', $q);
		$this->db->or_like('tch_staff_no', $q);
		$this->db->or_like('tch_fullname', $q);
		$this->db->or_like('tch_nric_no', $q);
		$this->db->or_like('tch_contact_no', $q);
		$this->db->or_like('tch_gender', $q);
		$this->db->or_like('tch_phone_no', $q);
		$this->db->or_like('tch_email', $q);
		$this->db->or_like('tch_race', $q);
		$this->db->or_like('tch_religion', $q);
		$this->db->or_like('tch_address', $q);
		$this->db->or_like('tch_postal_code', $q);
		$this->db->or_like('tch_city_id', $q);
		$this->db->or_like('tch_state_id', $q);
		$this->db->or_like('tch_country_id', $q);
		$this->db->or_like('school_id', $q);
		$this->db->or_like('create_at', $q);
		$this->db->or_like('update_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Teacher_model.php */
/* Location: ./application/models/Teacher_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-09 06:55:13 */