<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'user';
    public $id = 'user_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('user_id,user_username,user_email,email_verified_at,user_password,user_remember_token,role_id,school_id,user_avatar,created_at,updated_at');
        $this->datatables->from('user');

        $this->datatables->add_column('action', 
                anchor(site_url('user/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> View', array('class' => 'btn btn-success btn-sm', 'title' => 'view Record')).
                " | "
                .anchor(site_url('user/update/$1'),'<i class="mdi mdi-lead-pencil" aria-hidden="true"></i> Update', array('class' => 'btn btn-cyan btn-sm')).
                " | "
                .anchor(site_url('user/delete/$1'),'<i class="mdi mdi-delete-forever" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-sm delete-btn')), 'user_id');
        return $this->datatables->generate();

    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('user_id', $q);
		$this->db->or_like('user_username', $q);
		$this->db->or_like('user_email', $q);
		$this->db->or_like('email_verified_at', $q);
		$this->db->or_like('user_password', $q);
		$this->db->or_like('user_remember_token', $q);
		$this->db->or_like('role_id', $q);
		$this->db->or_like('school_id', $q);
		$this->db->or_like('user_avatar', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('user_id', $q);
		$this->db->or_like('user_username', $q);
		$this->db->or_like('user_email', $q);
		$this->db->or_like('email_verified_at', $q);
		$this->db->or_like('user_password', $q);
		$this->db->or_like('user_remember_token', $q);
		$this->db->or_like('role_id', $q);
		$this->db->or_like('school_id', $q);
		$this->db->or_like('user_avatar', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Codeigniter CRUD Generator 2020-03-07 15:32:57 */